### ISSUE TITLE
XPath text box does not adapt to multi-line strings

### ISSUE THREAD

**Issue by NightmareCorporation** [SmashPhil/XmlPatchHelper#1]
The text-field for inputting the XPath does not properly expand when writing a patch spanning multiple lines. 
This results in very cramped and unreadable text
![image](https://user-images.githubusercontent.com/19686118/210176524-f146984c-de41-4ef8-b11c-7b817633d7fd.png)

Happens on any resolution
`Defs/ThinkTreeDef[defName="MentalStateNonCritical"]/thinkRoot/subNodes/li[stateClass="MentalState_Manhunter"]/subNodes/li/subNodes/li[@Class="JobGiver_Manhunter"]`

Fix should be possible by using `Text.CalcHeight(string text, float width)` to calculate the needed height for a given text.

**Comment by SmashPhil** [comment]
Yea I've fixed this already but haven't pushed the update to steam yet.  Will push it soon-ish
